INFO:root:Server started on port 50051
INFO:root:
Updated Coordinates of Soldiers:
INFO:root:ID: 0, X: 8, Y: 4, Speed: 4, Commander: True, Alive: True
INFO:root:ID: 1, X: 7, Y: 0, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 2, X: 0, Y: 7, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 3, X: 4, Y: 0, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 4, X: 6, Y: 5, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 5, X: 9, Y: 7, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 6, X: 7, Y: 7, Speed: 4, Commander: False, Alive: True
INFO:root:ID: 7, X: 1, Y: 6, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 8, X: 9, Y: 3, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 9, X: 8, Y: 0, Speed: 3, Commander: False, Alive: True
INFO:root:
Battlefield status:
INFO:root:Battle Duration: 2 seconds
INFO:root:Soldier ID : 4 SAFE. Moved out of red zone to (5, 4)
INFO:root:Soldier ID : 6 DEAD
INFO:root:Missile ID: 0, Target X: 5, Target Y: 7, Radius: 3
INFO:root:
Updated Coordinates of Soldiers:
INFO:root:ID: 0, X: 8, Y: 4, Speed: 4, Commander: True, Alive: True
INFO:root:ID: 1, X: 7, Y: 0, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 2, X: 0, Y: 7, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 3, X: 4, Y: 0, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 4, X: 5, Y: 4, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 5, X: 9, Y: 7, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 7, X: 1, Y: 6, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 8, X: 9, Y: 3, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 9, X: 8, Y: 0, Speed: 3, Commander: False, Alive: True
ERROR:grpc._server:Exception iterating responses: 'NoneType' object is not an iterator
Traceback (most recent call last):
  File "/Users/apurav/anaconda3/lib/python3.11/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not an iterator
INFO:root:
Battlefield status:
INFO:root:Battle Duration: 4 seconds
INFO:root:Soldier ID : 2 DEAD
INFO:root:Soldier ID : 7 SAFE. Moved out of red zone to (0, 5)
INFO:root:Missile ID: 1, Target X: 3, Target Y: 9, Radius: 4
INFO:root:
Updated Coordinates of Soldiers:
INFO:root:ID: 0, X: 8, Y: 4, Speed: 4, Commander: True, Alive: True
INFO:root:ID: 1, X: 7, Y: 0, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 3, X: 4, Y: 0, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 4, X: 5, Y: 4, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 5, X: 9, Y: 7, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 7, X: 0, Y: 5, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 8, X: 9, Y: 3, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 9, X: 8, Y: 0, Speed: 3, Commander: False, Alive: True
ERROR:grpc._server:Exception iterating responses: 'NoneType' object is not an iterator
Traceback (most recent call last):
  File "/Users/apurav/anaconda3/lib/python3.11/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not an iterator
INFO:root:
Battlefield status:
INFO:root:Battle Duration: 6 seconds
INFO:root:Soldier ID : 7 SAFE. Moved out of red zone to (0, 4)
INFO:root:Missile ID: 2, Target X: 0, Target Y: 6, Radius: 2
INFO:root:
Updated Coordinates of Soldiers:
INFO:root:ID: 0, X: 8, Y: 4, Speed: 4, Commander: True, Alive: True
INFO:root:ID: 1, X: 7, Y: 0, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 3, X: 4, Y: 0, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 4, X: 5, Y: 4, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 5, X: 9, Y: 7, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 7, X: 0, Y: 4, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 8, X: 9, Y: 3, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 9, X: 8, Y: 0, Speed: 3, Commander: False, Alive: True
ERROR:grpc._server:Exception iterating responses: 'NoneType' object is not an iterator
Traceback (most recent call last):
  File "/Users/apurav/anaconda3/lib/python3.11/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not an iterator
INFO:root:
Updated Coordinates of Soldiers:
INFO:root:ID: 0, X: 8, Y: 4, Speed: 4, Commander: True, Alive: True
INFO:root:ID: 1, X: 7, Y: 0, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 3, X: 4, Y: 0, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 4, X: 5, Y: 4, Speed: 1, Commander: False, Alive: True
INFO:root:ID: 5, X: 9, Y: 7, Speed: 0, Commander: False, Alive: True
INFO:root:ID: 7, X: 0, Y: 4, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 8, X: 9, Y: 3, Speed: 2, Commander: False, Alive: True
INFO:root:ID: 9, X: 8, Y: 0, Speed: 3, Commander: False, Alive: True
